name: Build

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

  rerun:
    name: Re Run
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          curl -H "Accept:application/vnd.github.antiope-preview+json" https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_REF/check-runs
